# Generated by Django 4.0.1 on 2022-01-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeItem', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(1, 'Comprado'), (2, 'Aguardando Orçamento'), (3, 'Recebido')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
