# Generated by Django 4.0.1 on 2022-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observação',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
