# Generated by Django 4.0.1 on 2022-01-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_observação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='anexo01',
            new_name='orçamento01',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='anexo02',
            new_name='orçamento02',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='anexo03',
            new_name='orçamento03',
        ),
    ]
