# Generated by Django 4.0.1 on 2022-01-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_orçamento01_alter_task_orçamento02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='orçamento01',
            field=models.ImageField(null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orçamento02',
            field=models.ImageField(null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orçamento03',
            field=models.ImageField(null=True, upload_to='anexos/'),
        ),
    ]
