# Generated by Django 4.0.1 on 2022-01-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_orçamento01_alter_task_orçamento02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='orçamento01',
            field=models.FileField(null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orçamento02',
            field=models.FileField(null=True, upload_to='anexos/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='orçamento03',
            field=models.FileField(null=True, upload_to='anexos/'),
        ),
    ]
