# Generated by Django 4.0.1 on 2022-01-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_orçamento01_alter_task_orçamento02_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='orçamento01',
            new_name='orcamento01',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='orçamento02',
            new_name='orcamento02',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='orçamento03',
            new_name='orcamento03',
        ),
    ]
