# Generated by Django 4.0.1 on 2022-01-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_nomeitem_task_nome_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='nome',
            new_name='nome_item',
        ),
    ]
