# Generated by Django 4.0.1 on 2022-03-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_nome_item_task_nomeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='nomeItem',
            field=models.CharField(max_length=255, verbose_name='Nome do item: '),
        ),
    ]
